version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes: # добавляем volume к папке, где хранится локально вся БД
      - pg_volume:/var/lib/postgresql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # добавляем директорию со скриптами для инициализации
    ports:
      - 5432:5432

  adminer: # использую adminer, но это необязательно, если расшарить порты от БД PSQL.
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_volume: {}
  c3s_volume: {}
