version: '3.1'

services:

  mongo:
    image: mongo:4.4.4-bionic
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: admin
    #  MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      #- mongo_volume:/data/db # добавляем volume к папке, где хранится локально вся БД
      - ./data.csv:/data.csv
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # добавляем директорию со скриптами для инициализации

  mongo-express: # админка mongo
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: admin

volumes:
  mongo_volume: {}
