version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes: # добавляем volume к папке, где хранится локально вся БД
      - pg_volume:/var/lib/postgresql

  adminer: # использую adminer, но это необязательно, если расшарить порты от БД PSQL.
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_volume: {}
